services:
  redis:
    image: redis:7.4.1-alpine
    ports:
      - "6379:6379"
    volumes:
    - redis_data:/data
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
  bot:
    build:
      context: .
      dockerfile: ./bot/Dockerfile
    env_file:
      - .env
    depends_on:
      - redis
      - api
volumes:
  redis_data:
